### ISSUE TITLE
Incorrect footer position

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology-theme#18]
![image](https://cloud.githubusercontent.com/assets/1902527/22815281/67e98c5a-ef95-11e6-8b7c-3d09ff85c966.png)

Footer covers the `Submit` button and prevents it from being clicked. #16 has been reverted.

**Comment by nicholette** [comment]
@fonglh @allenwq how should I go about recreating this?

**Comment by fonglh** [comment]
Try creating a new programming question

**Comment by allenwq** [comment]
In the programming question creation page,  if you make the content longer
than the sidebar, I think you will see it.

**Comment by nicholette** [comment]
👌
